# Generated by Django 6.0.1 on 2026-01-30 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_customer_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('product_category', models.CharField(choices=[('PRINTERS', 'Printers'), ('LABELS', 'Labels'), ('RFID', 'RFID'), ('SCANNERS', 'Scanners'), ('SOFTWARE', 'Software')], max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('deal_type', models.CharField(choices=[('NEW', 'New'), ('EXPANSION', 'Expansion'), ('REPLACEMENT', 'Replacement')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='DRAFT', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.partnerorganisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='deals.deal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
