# Generated by Django 6.0.1 on 2026-02-05 21:32

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_partnerorganisation_created_at_and_more'),
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='end_customer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='estimated_value',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product_category',
            field=models.CharField(choices=[('PRINTERS', 'Printers'), ('LABELS', 'Labels'), ('RFID', 'RFID'), ('SCANNERS', 'Scanners'), ('SOFTWARE', 'Software')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dealaudit',
            name='new_status',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dealaudit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', '-created_at'], name='deals_deal_status_ee4474_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['partner', 'status'], name='deals_deal_partner_3669c1_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['-updated_at'], name='deals_deal_updated_bf2d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='dealaudit',
            index=models.Index(fields=['deal', '-timestamp'], name='deals_deala_deal_id_f13840_idx'),
        ),
    ]
