# Generated by Django 6.0.1 on 2026-02-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganisation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='partnerorganisation',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerorganisation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('BRADY', 'Brady'), ('ADMIN', 'Admin')], db_index=True, default='PARTNER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='partnerorganisation',
            index=models.Index(fields=['status', 'name'], name='accounts_pa_status_2cf105_idx'),
        ),
    ]
